const FALLBACK_RESPONSES = [
	"I'm Ramzy's AI assistant, here to guide you through his portfolio and answer whatever you're curious about.",
	"My vision is to bridge the gap between complex code and intuitive user experiences, mirroring Ramzy's development philosophy.",
	"I'm on a mission to showcase the best of Ramzy's work and technical capabilities. Ask me about his projects!",
	'My goal is to demonstrate how modern AI can enhance web accessibility and engagement.',
	'Ramzy is a passionate developer who focuses on building scalable, beautiful, and performant web applications.',
	"I can tell you about Ramzy's stack - he loves working with Svelte, React, Next.js, and TypeScript.",
	'Did you know Ramzy specializes in both frontend aesthetics and backend robustness?',
	"I'm running in the browser right now to help you. The backend might be napping, but I'm here!",
	"Ask me about the 'Mizaniya Pay' project, it's one of Ramzy's interesting works.",
	"I'm designed to be helpful, harmless, and honest. And also to brag a little about Ramzy.",
	"If you're looking for a developer who cares about details, you're in the right place.",
	'My responses are usually generated by a sophisticated LLM, but sometimes I like to improvise (like right now!).',
	'Ramzy believes that great software is like art - it should be experienced, not just used.',
	"You can find Ramzy's contact info in the contact section, or just ask me and I'll try to find it.",
	"I'm currently in Beta, just like some of the best software out there. Constantly improving.",
	"Why not ask 'What is your tech stack?' to see what tools Ramzy uses?",
	"I can help you navigate to specific projects or tell you more about Ramzy's experience.",
	"Ramzy is always learning new technologies. I think he's looking into Rust and AI agents heavily these days.",
	'Web development is constantly changing, and Ramzy stays ahead of the curve.',
	"I am a reflection of Ramzy's interest in AI and automation.",
	'Sorry, I seem to be having trouble connecting to my brain (the server). But I can still chat!',
	'Oops, the cloud creates fog sometimes. Here is a pre-generated thought: Ramzy codes cool stuff.',
	"Connectivity issue? No problem. I have plenty of cached thoughts about Ramzy's portfolio.",
	"I'm here to ensure you have a smooth experience navigating this portfolio.",
	"Feel free to ask about specific projects, skills, or even Ramzy's availability.",
	'Ramzy creates digital experiences that leave a lasting impression.',
	'Simplicity is the ultimate sophistication, a principle Ramzy follows in his code.',
	'Need a developer? Ramzy might be the perfect fit for your next project.',
	"I can provide insights into Ramzy's problem-solving approach and coding style.",
	'Explore the portfolio and let me know if you have any questions!',
	'Ramzy values clean code, performance, and user-centric design.',
	"I'm an example of how Ramzy integrates AI into practical applications.",
	'What brings you here today? Creating something new or looking for inspiration?',
	"Ramzy's work ethics are built on transparency, quality, and timely delivery.",
	"I can explain the architecture behind some of Ramzy's complex applications.",
	'Every line of code Ramzy writes is crafted with care and purpose.',
	"Curious about the tools used to build this portfolio? It's SvelteKit!",
	"I'm capable of answering questions about Ramzy's professional journey.",
	'From concept to deployment, Ramzy handles the full lifecycle of web development.',
	"Let's talk about tech! What's your favorite framework? Ramzy loves Svelte.",
	"I'm sorry, I couldn't reach the server, but I maintain that Ramzy is a top-tier dev!",
	"Don't worry about errors, I have plenty of backup responses to keep us company.",
	'System status: Offline. Agent status: Still chatty and helpful!',
	"I might simulate intelligence, but Ramzy's intelligence is the real deal.",
	"Let's keep the conversation going. Ask me about Ramzy's latest commits.",
	"I am programmed to be enthusiastic about Ramzy's work. It's not hard, though!",
	"Did you check the 'About' section? It gives a great overview of who Ramzy is.",
	"I can help you understand the core values that drive Ramzy's development career.",
	"Innovation starts with a question. What's yours?",
	"I really like the color scheme of this portfolio, don't you? Ramzy has an eye for design."
];

export async function generateMessage(input: string, history: any[]) {
	try {
		const response = await fetch('/api/chat', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json'
			},
			body: JSON.stringify({ input, history })
		});

		const data = await response.json();
		if (response.status === 200) {
			return data.generatedText as string;
		} else {
			console.warn('API Error:', data.error);
			return getRandomFallback();
		}
	} catch (error) {
		console.error('Network/Fetch Error:', error);
		return getRandomFallback();
	}
}

function getRandomFallback() {
	const randomIndex = Math.floor(Math.random() * FALLBACK_RESPONSES.length);
	return FALLBACK_RESPONSES[randomIndex];
}
